<a href="https://colab.research.google.com/github/tanupat085/test/blob/master/tantexhday2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [38]:
data = pd.read_csv('drive/My Drive/mnist/train.csv')

In [26]:
data

array([[2, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [39]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [40]:
X_train[:,0].shape

(784,)

In [41]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [42]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [43]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[5 0 3 ... 0 0 5] [4 3 0 ... 1 1 4]
0.08617073170731707
Iteration:  10
[9 0 3 ... 1 1 5] [4 3 0 ... 1 1 4]
0.13707317073170733
Iteration:  20
[9 0 3 ... 1 1 5] [4 3 0 ... 1 1 4]
0.19790243902439025
Iteration:  30
[9 0 3 ... 1 1 5] [4 3 0 ... 1 1 4]
0.26702439024390245
Iteration:  40
[9 0 3 ... 1 1 5] [4 3 0 ... 1 1 4]
0.32751219512195123
Iteration:  50
[9 0 3 ... 1 1 5] [4 3 0 ... 1 1 4]
0.38602439024390245
Iteration:  60
[9 0 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.4564878048780488
Iteration:  70
[9 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.5287317073170732
Iteration:  80
[4 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.5718292682926829
Iteration:  90
[4 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.6056341463414634
Iteration:  100
[4 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.6312439024390244
Iteration:  110
[4 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.6523658536585366
Iteration:  120
[4 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.6701951219512196
Iteration:  130
[4 3 3 ... 1 1 4] [4 3 0 ... 1 1 4]
0.684439024390244
Iteration:  